### ISSUE TITLE
TS Error: i18n.global.t

### ISSUE THREAD

**Issue by fenyuluoshang** [intlify/vue-i18n-next#1219]
### Reporting a bug?

use `i18n.global.t` has report A TS Error

```
This expression is not callable.
  Each member of the union type 'ComposerTranslation<{}, string, RemoveIndexSignature<{ [x: string]: LocaleMessageValue<VueMessageType>; }>, never, never, never> | VueI18nTranslation<...>' has signatures, but none of those signatures are compatible with each other.ts(2349)
```

### Expected behavior

to use i18n.t out of vue component ,it will get problem, like `t` has two type `ComposerTranslation` and `VueI18nTranslation`

### Reproduction

```
const i18n = createI18n({ ... })

i18n.global.t("xxx.xxx.xxx")
```

### System Info

```shell
System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 8.74 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.17.1/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Firefox: 106.0.5
    Safari: 16.1
  npmPackages:
    @vue/cli-plugin-babel: ~5.0.0 => 5.0.4 
    @vue/cli-plugin-e2e-cypress: ~5.0.0 => 5.0.4 
    @vue/cli-plugin-eslint: ~5.0.0 => 5.0.4 
    @vue/cli-plugin-router: ~5.0.0 => 5.0.4 
    @vue/cli-plugin-typescript: ~5.0.0 => 5.0.4 
    @vue/cli-plugin-unit-jest: ~5.0.0 => 5.0.4 
    @vue/cli-service: ~5.0.0 => 5.0.4 
    @vue/eslint-config-airbnb-with-typescript: ^7.0.0 => 7.0.0 
    @vue/eslint-config-standard: ^7.0.0 => 7.0.0 
    @vue/eslint-config-typescript: ^9.1.0 => 9.1.0 
    @vue/test-utils: ^2.0.0-0 => 2.0.0 
    @vue/vue3-jest: ^27.0.0-alpha.1 => 27.0.0 
    vue: ^3.2.13 => 3.2.36 
    vue-eslint-parser: ^9.0.2 => 9.0.2 
    vue-i18n: ^9.2.2 => 9.2.2 
    vue-i18n-extract: ^2.0.7 => 2.0.7 
    vue-router: ^4.1.5 => 4.1.5 
    vue3-infinite-scroll-good: ^1.0.2 => 1.0.2
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kazupon** [comment]
Thank you for your reporting!

Unfortunately, I could not reproduce this issue
In my enviroment (vite + vue),  `t` is correctly type inferred with using `legacy: false` in `createI18n`.

main.ts:
![image.png](https://volta.s3.fr-par.scw.cloud/image_30f44f5026.png)

Vue component: 
![image.png](https://volta.s3.fr-par.scw.cloud/image_ff0c695dfc.png)

Could you give us your minimum reproduction codes with github repo or stackbliz please?

**Comment by rvaliev** [comment]
Same here

**Comment by kazupon** [comment]
Close due to in-activity
If you would have issue, please give us to **minimual** reproduction codes with github repo or stackblize as new issue.

Thanks!

**Comment by WangJincheng4869** [comment]
我也遇到了同样的问题，请问是要在项目中添加什么配置才能使用`i18n.global.t`吗？   
（I also encountered the same problem. What configuration should I add to the project to use `i18n.global.t`?）
![image](https://user-images.githubusercontent.com/41162158/213108490-e078faf4-044a-4619-b7b7-1a44ff3cfa8a.png)

**Comment by fenyuluoshang** [comment]
> 我也遇到了同样的问题，请问是要在项目中添加什么配置才能使用`i18n.global.t`吗？ （I also encountered the same problem. What configuration should I add to the project to use `i18n.global.t`?） ![image](https://user-images.githubusercontent.com/41162158/213108490-e078faf4-044a-4619-b7b7-1a44ff3cfa8a.png)

No idea about that, 我只是正常使用，前面希望我提供更多信息，我尝试找了一下原因，两份冲突内容都在同一个TS描述文件，看起来无解，我只能用 `xxx as xxx` 来临时解决

**Comment by dinghui-wang** [comment]
This error is caused by the initial parameter not being correctly assigned when using the inject(key, initial) method, resulting in a null value error. The inject(key, initial) method is a form of dependency injection, which requires specifying a key name key and an initial value initial for injecting dependencies in subsequent code. If the initial parameter is not assigned or assigned with a null value, a null value error may occur in subsequent code. Therefore, when using the inject(key, initial) method, it is important to ensure that the initial parameter is correctly assigned.

What I did.
![image](https://github.com/intlify/vue-i18n-next/assets/61412262/5fa71057-2589-4ffe-9f55-b3cfba84850e)

**Comment by dinghui-wang** [comment]
This error is caused by the initial parameter not being correctly assigned when using the inject(key, initial) method, resulting in a null value error. The inject(key, initial) method is a form of dependency injection, which requires specifying a key name key and an initial value initial for injecting dependencies in subsequent code. If the initial parameter is not assigned or assigned with a null value, a null value error may occur in subsequent code. Therefore, when using the inject(key, initial) method, it is important to ensure that the initial parameter is correctly assigned.

so use ! to aviod null/undefined value.

**Comment by Evertvdw** [comment]
I am still having this issue, I am using TS 5.1.3 and `vue-tsc@1.8.4` together with `vue-i18n@9.3.0-beta.24`. Is there a workaround for this?
