### ISSUE TITLE
node_modules/.pnpm/vue-i18n@9.5.0_vue@3.3.4/node_modules/vue-i18n/dist/vue-i18n.runtime.mjs (303:20) A comment "/* #__PURE__*/" in "node_modules/.pnpm/vue-i18n@9.5.0_vue@3.3.4/node_modules/vue-i18n/dist/vue-i18n.runtime.mjs" contains an annotation that Rollup cannot interpret due to the position of the comment. The comment will be removed to avoid issues.

### ISSUE THREAD

**Issue by newives** [intlify/vue-i18n-next#1599]
### Reporting a bug?

Packaging error
```
pnpm build
```

### Expected behavior

Packaging without error

### Reproduction

https://stackblitz.com/edit/vitejs-vite-jq7jch?file=src%2Fmain.ts

### System Info

```shell
vite 5
mac
google
```

### Screenshot

![图片](https://github.com/intlify/vue-i18n-next/assets/81661030/725b5c77-c53e-4018-bbd0-41049e7a0dfa)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussions](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by sapphi-red** [comment]
Here's the places the warning is pointing at:

- https://github.com/intlify/vue-i18n-next/blob/d8bd388b60dc06fbb430c4c4855819ca16362735/packages/vue-i18n-core/src/composer.ts#L1773-L1780
- https://github.com/intlify/vue-i18n-next/blob/d8bd388b60dc06fbb430c4c4855819ca16362735/packages/core-base/src/context.ts#L417-L424
- https://github.com/intlify/vue-i18n-next/blob/d8bd388b60dc06fbb430c4c4855819ca16362735/packages/core-base/src/compilation.ts#L55-L61

`/* #__PURE__ */` indicates the next expression after it can be removed if the evaluated value of that expression is not used. So `/* #__PURE__ */` should be placed immediately before the function call, not before the function declarations/expressions. Function declarations/expressions are *pure* in nature.

You can also just swap `/* #__PURE__ */` with `/* #__NO_SIDE_EFFECTS__ */` which works as you expect. But it's only supported by rollup and esbuild currently.

**Comment by Mohith-113** [comment]
This error is caused by a comment annotation in the vue-i18n runtime module that Rollup cannot interpret. The comment is supposed to mark a pure function, but it is placed in a wrong position. [Rollup will remove the comment to avoid issues, but this may affect the tree-shaking and bundling process](https://github.com/rollup/rollup/issues/3334)[1](https://github.com/rollup/rollup/issues/3334).

To fix this error, you have a few options:

You can try to update your vite and vue-i18n versions to the latest ones, and see if the error is resolved. [Some users have reported that this worked for them](https://github.com/rollup/rollup/issues/3334)[2](https://bing.com/search?q=how+to+fix+rollup+comment+annotation+error).
You can use the @rollup/plugin-replace plugin to replace the comment annotation with an empty string in your rollup.config.js file. This will prevent Rollup from removing the comment and causing issues. You can find an example of how to do this in [this GitHub issue](https://stackoverflow.com/questions/73197460/error-could-not-resolve-entry-module-react-rollup).
You can use the @rollup/plugin-strip plugin to strip all comments from the vue-i18n runtime module in your rollup.config.js file. This will also prevent Rollup from removing the comment and causing issues. You can find an example of how to do this in [this Stack Overflow answer](https://stackoverflow.com/questions/65384754/error-err-module-not-found-cannot-find-module).
I hope this information helps you fix the error and use vue-i18n with vite successfully. 😊

**Comment by newives** [comment]
Hey, the stable version of vite5 will be released soon. Does the author have an official solution for this? Because this warning will be reported every time when packaging.

**Comment by kazupon** [comment]
Hi!
I’m going to fix this issue.
Just a little busy until around mid Nov, so I have after work of conference, and I have meetup event as speaker.
I'll fix when those are done.

vue-i18n and intlify project is OSS
if you have a time, you can contribute :)

**Comment by newives** [comment]
PTAL https://github.com/intlify/vue-i18n-next/pull/1623
I conducted a local test and after modification, the warning no longer appears when packaging.
