### ISSUE TITLE
"unexpected error" when not adding .use(createI18n())

### ISSUE THREAD

**Issue by michaelzangl** [intlify/vue-i18n-next#161]
### vue & vue-i18n version
```
"vue": "3.0.2",
"vue-i18n": "9.0.0-beta.6"
"@intlify/vue-i18n-loader": "2.0.0-beta.1",
"@vue/cli": "4.5.8",
```

### Steps to reproduce

Add vue-i18n dependencies. In your component, include:
```
  setup() {
    return useI18n()
  },
```

Do not include any global config in your main app (no `createI18n`)

### What is Expected?
An error indicating what happened and suggesting a solution to fix this.

### What is actually happening?
The console says "unexpected error"

This is caused [by](https://github.com/intlify/vue-i18n-next/blob/83ca300ad737900b3a5f15e57e80fa9783558d95/src/i18n.ts#L472):
```
throw createI18nError(15);
```
In this case, a more descriptive error message should be printed.

**Comment by kazupon** [comment]
Thank you for your feedback!


> This is caused [by](https://github.com/intlify/vue-i18n-next/blob/83ca300ad737900b3a5f15e57e80fa9783558d95/src/i18n.ts#L472):
> 
> ```
> throw createI18nError(15);
> ```
> 
> In this case, a more descriptive error message should be printed.


vue-i18n-next is **the error code** only for production build. 
This is to remove error messages and reduce the code size so that you can optimize the bundle size of our Vue app.

However, the error when we forget to execute `createI18n` is hard to understand. You need to define a special error code and error message (for development).
