### ISSUE TITLE
Allow `globalInjection` to provide locally-scoped translation function

### ISSUE THREAD

**Issue by andresberrios** [intlify/vue-i18n-next#339]
Hello! In our project we use custom `<i18n>` blocks in single file components to provide the messages for each component. We would like to use the `globalInjection` option to have access to the `$t` function in all our templates without having to call `useI18n()` and return the `t` function from the `setup` function of each of our components. The problem is that the globally injected `$t` function is bound to the global messages scope, and not the local scope of the component.

It would be great if the `$t` function could use the local scope for messages and fall back to the global scope if a message is missing in the local scope.

Is this possible to implement in our own code somehow? Could it be supported by the library at some point?
Thanks!!

**Comment by kazupon** [comment]
Thank you for your feedback!

Unfortunately, due to the limitations of the Vue 3 API, it's not possible to implicitly inject local scope. :disappointed: 
We use `app.config.globalProperties` to achieve this, but we can't handle locale messages in i18n custom blocks.
In the Compostion API, you need to call `useI18n` in your `setup`(or `<script setup>`).

Thanks!

**Comment by andresberrios** [comment]
I see, thanks for your reply. In the end we are using `useI18n` and returning the `t` function from our `setup` function, and it's working really well. Thanks for your work on this awesome library. Also, I love the DIO and JoJo references in the docs :)
