### ISSUE TITLE
Using composition with legacy in local scopes

### ISSUE THREAD

**Issue by daniesg** [intlify/vue-i18n-next#416]
It looks like the composition API doesn't work well with legacy when it comes to locale scopes. I have an app where I generally want i18n enabled everywhere with local scopes. So it's common to see a component look like this:
```
import messages from '../ path to locales/ thing.js';

export default {
  ...
  i18n: { messages }
  ...
}
``` 

There are a few places where I actually want to use the composition API. Essentially I have a composition function that does some common work and needs it's own translations. About 4-5 components use this composition function.

So the composition function looks like this:
```
import messages from '../.locales for this function.js';
import { useI18n } from 'vue-i18n';
import { computed, ref } from 'vue';

export default function(options = {}) {
  const { t } = useI18n({ messages });
  ... // do some work and return translations
```

And the component that uses this function looks like this:
```
  import messages from "../locales for this component.js";
  import { mapState } from 'vuex';
  import { ref, computed } from 'vue';
  import myCompositionFunction from '../my-composition-function.js';

  export default {
    ...
    i18n: { messages },
    setup: function() {
      let thing = myCompositionFunction('stuff');
      ...
    },
    ...
  }
```

My global setup looks like this:
```
  const i18n = createI18n({
    locale: 'en',
    fallbackLocale: 'en',
    messages,
    silentFallbackWarn: true,
    silentTranslationWarn: true,
    legacy: false,
    globalInjection: true
  });
```

I'm not sure if this is a feature request or bug, but shouldn't this work? Because it definitely doesn't. Now the only translations I can see are global translations in all of my components. Even the components that don't use/have a setup function. Is this a use case not supported or am I doing something wrong.

**Module versions:**
 - `vue`: 3.0.9
 - `vue-i18n`: 9.0.0

**Comment by kazupon** [comment]
Thank you for your feedback!

Unfortunately, in vue-i18n v9, it is not possible to support i18n in Vue applications using both Composition API Style and Legacy API Style at the same time.

This is the intention of vue-i18n v9.
You should unify your API code usage style to one of them.

Several of the reasons for the restriction are as follows:

- To ensure maintainability of i18n support in Vue applications:
  - Code that mixes Composition API Style and Legacy API Style will be chaotic.
- To make it easier to support the Option Style API in Vue.js when it is dropped in the future
  - Legacy API is vue-i18n's API for the Option Style API, and vue-i18n is planning to drop Legacy API as well as Vue.
- Architectural limitations of vue-i18n's i18n resource management: 
  - it's scoped by global & local, and there is a mismatch between Composition API Style and Legacy API Style due to subtle differences.

**Comment by gagarine** [comment]
The doc is not really clear that vue-18n composition API mode and legacy API mode are not compatible.
