### ISSUE TITLE
Compilation fails when text includes @

### ISSUE THREAD

**Issue by finnmich** [intlify/vue-i18n-next#531]
The following error is shown if the external json file with the messages has an `@` in the text.

Syntax Error: Final loader (./node_modules/@intlify/vue-i18n-loader/lib/index.js) didn't return a Buffer or String

`
{
  "test": "Send us an e-mail on test@test.no"
}
`

Throws the error.

`
{
  "test": "Send us an e-mail on testtest.no"
}
`

Works fine.

**Comment by kazupon** [comment]
Thank you for your reporting!
`@` is a special character from `vue-i18n@v9`
You need to use [literal interpolation](https://vue-i18n.intlify.dev/guide/essentials/syntax.html#literal-interpolation)
You can avoid with how to use the below:

```
 "test": "Send us an e-mail on test{'@'}test.no" }
```

Thanks!

**Comment by philipp-rudloff-sendcloud** [comment]
The error message for this needs to be much, much clearer. I spent well over an hour finding out why migrating a vue-i18n setup to Vue 3 always got me back to the following error message:

> Final loader (./node_modules/@intlify/vue-i18n-loader/lib/index.js) didn't return a Buffer or String

and it was simply a translation message of the form “Contact info@example.com”.

I would also really like to turn this off completely. I really don’t want something as cryptic as `{'@'}` to leak into my translation files which get handed over to translators.

**Comment by nicooprat** [comment]
I think I finally found a way to circumvent this by using the `messageResolver` option of `createI18n()`:

```ts
import { get } from 'lodash';

const i18n = createI18n({
    // Prevent '@' character from being used as linked messages
    messageResolver: (obj, path) => get(obj, path, '')?.replaceAll(/@/g, "{'@'}") || null,
})
```

This way every `@` character will be automatically escaped before vue-i18n evaluates it. I hope I didn't miss any edge case.

I think this could be added in the docs as a clue because it can makes migration from v8 to v9 almost impossible.

**Comment by Dorianslavov** [comment]
> I think I finally found a way to circumvent this by using the `messageResolver` option of `createI18n()`:
> 
> ```ts
> import { get } from 'lodash';
> 
> const i18n = createI18n({
>     // Prevent '@' character from being used as linked messages
>     messageResolver: (obj, path) => get(obj, path, '')?.replaceAll(/@/g, "{'@'}") || null,
> })
> ```
> 
> This way every `@` character will be automatically escaped before vue-i18n evaluates it. I hope I didn't miss any edge case.
> 
> I think this could be added in the docs as a clue because it can makes migration from v8 to v9 almost impossible.

Doesn't seem to work for me

<img width="1187" alt="image" src="https://github.com/intlify/vue-i18n-next/assets/25179716/20b43c67-8fe0-4c35-8b44-47f1312ecb46">

**Comment by nicooprat** [comment]
Hard to tell, you could set a `debugger` in the `messageResolver` function to see what's going on ;) We don't use translations in components, I may not know a specific behavior to this.

**Comment by Dorianslavov** [comment]
> Hard to tell, you could set a `debugger` in the `messageResolver` function to see what's going on ;) We don't use translations in components, I may not know a specific behavior to this.

the weird thing is that even If I set debugger, console logs, etc... nothing happens as if it doesn't go through the `messageResolver`. Any ideas ?

**Comment by nicooprat** [comment]
Does it work for classic translation files, I mean not-in-component blocks?

**Comment by chojnicki** [comment]
@kazupon why there is no option to just disable linking via @ sign if we are not using this functionality at all? What's worse - I'm using petite-vue-i18n that supposed to be very basic, but it still uses "@" in message resolver. If petite is basic, keep it basic. Sure I can overwrite that in message resolver via replacing @ to literals, but this should not be necessary.
I will remember to use "{'@'}" inside translations, but only because I'm developer. I will have to explain this to multiple translators, and mistakes will be easy to make :(

**Comment by thany** [comment]
Can this issue please be reopened? We need a way to disable linking. That's basically it.

I can't reasonably tell the customer to go through all their translations and replace `@` by `{'@'}` just because "some package" started demanding it (mind you, it worked fine in vue-i18n for Vue 2).

Just because there's a workaround, doesn't mean the issue has dissappeared.

**Comment by wnmzzzz** [comment]
Agreed. @ is an incredibly bad choice for a special character, since the literal @ would appear quite a bit in text. And the resulting error message is very cryptic to boot.

It should either be changed entirely to a character or character sequence unlikely to appear in text, or there should be a way to configure the character used on an application level.

**Comment by LukeBridgesATG** [comment]
Adding my weight behind being able to disable the @ linking or specifying that character in config somewhere.

**Comment by alessioacella** [comment]
Same issue here — handling @ has become unnecessarily painful. I can't reasonably ask the client to go through all their translations and replace @ with {'@'} just because some package started requiring it — especially considering it worked perfectly fine in vue-i18n for Vue 2.

**Comment by wnmzzzz** [comment]
I suspect that comments on a closed issue are not very closely monitored. Maybe it would be better to create a separate Issue with an enhancement request, rather than a bugreport.

**Comment by ayu-exorcist** [comment]
> I think I finally found a way to circumvent this by using the `messageResolver` option of `createI18n()`:我想我终于找到了一种通过使用 `createI18n（）` 的 `messageResolver` 选项来规避这个问题的方法：
> 
```javascript
import { get } from 'lodash';

const i18n = createI18n({
    // Prevent '@' character from being used as linked messages
    messageResolver: (obj, path) => get(obj, path, '')?.replaceAll(/@/g, "{'@'}") || null,
})
```
>
> This way every `@` character will be automatically escaped before vue-i18n evaluates it. I hope I didn't miss any edge case.这样，每个 `@` 字符都会在 vue-i18n 评估之前自动转义。我希望我没有错过任何边缘情况。
> 
> I think this could be added in the docs as a clue because it can makes migration from v8 to v9 almost impossible.我认为这可以添加到文档中作为线索，因为它几乎可以使从 v8 迁移到 v9 变得不可能。

**Improve**:
```javascript
import { get } from 'lodash';

const i18n = createI18n({
    // https://vue-i18n.intlify.dev/guide/essentials/syntax.html#special-characters
    messageResolver: (obj, path) => return get(obj, path, '').replace(/[{}@$|]/g, (match) => `{'${match}'}`) || null,
})
```

**Comment by thany** [comment]
I'm not sure why this issue got closed? The workaround mentioned, while appreciated of course, is well and truly a *workaround*. Not a solution.

**Comment by wnmzzzz** [comment]
I have created a feature request, proposing an improvement to the handling of the @ Character. Anyone still following this issue, feel free to comment on #2214 if this is still an issue for you.

**Comment by dimiliev** [comment]
This needs to be reopened. Please consider logging/throwing proper errors. What makes it even worse is that there is no error in dev mode, so going to production with this can break the whole site with a 500 error. I just spent two hours trying to figure out why our staging environment is down, and this is the third time this has happened this year.
