### ISSUE TITLE
follow up with #669 

### ISSUE THREAD

**Issue by gwang74** [intlify/vue-i18n-next#736]
### Reporting a bug?

#669 
Sorry for the late reply. it is a [simple demo](https://github.com/gwang74/i18n-next-demo).

### Expected behavior

global change with https://unpkg.com/vue-i18n@9.1.7/dist/vue-i18n.global.prod.js

### Reproduction

https://github.com/gwang74/i18n-next-demo

### System Info

```shell
vue@3.2.11
vue-i18n@9.1.7
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by kazupon** [comment]
@gwang74 
I could check it!
Indeed, This is a bug...

Thank you for your reproduction repo! :)

**Comment by PeterAlfredLee** [comment]
Hi @kazupon
I'm not that familiar with `terser`, but I still think this problem is caused by tree-shaking.
I think rollup/terser believe the call of `trackReactivityValues` is meaningless, it was removed with tree-shaking.
Maybe we should find a way to make the call `trackReactivityValues` not be tree-shaked.

**Comment by PeterAlfredLee** [comment]
@kazupon 

> yes, We need to find out why it's tree-shaked.

I think I found it.

It's caused by terser option `pure_getters: true`. See [terser doc](https://github.com/terser/terser#readme), it says:
> pure_getters (default: "strict") -- If you pass true for this, Terser will assume that object property access (e.g. foo.bar or foo["bar"]) doesn't have any side effects. Specify "strict" to treat foo.bar as side-effect-free only when foo is certain to not throw, i.e. not null or undefined.

I just tested, if you remove this line : 
https://github.com/intlify/vue-i18n-next/blob/6154508272590ddd1b65ac297c2690b7cd1cca53/rollup.config.js#L279

The call of trackReactivityValues will not be removed from `vue-i18n.global.prod.js` and everything works fine.
