### ISSUE TITLE
devtools-if and vue-devtools in production build

### ISSUE THREAD

**Issue by FireMasterK** [intlify/vue-i18n-next#850]
### Reporting a bug?

`devtools-if` and `vue-devtools` are included in a production build

### Expected behavior

Not have a build `devtools-if` and `vue-devtools`  unless this behaviour is intentional.

### Reproduction

git clone https://github.com/TeamPiped/Piped
cd Piped
yarn install
yarn build
cat dist/js/*.js | grep "v9.2.0-beta.25"

### System Info

```shell
System:
    OS: Linux 5.15 undefined
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 375.56 MB / 13.59 GB
    Container: Yes
    Shell: 5.1.12 - /bin/bash
  Binaries:
    Node: 17.3.0 - /usr/bin/node
    Yarn: 1.22.17 - /usr/bin/yarn
    npm: 8.3.0 - /usr/bin/npm
  Browsers:
    Brave Browser: 96.1.33.106
    Chromium: 96.0.4664.110
    Firefox: 95.0.2
  npmPackages:
    @intlify/vue-i18n-loader: ^4.1.0 => 4.1.0 
    @vue/cli-plugin-babel: ^4.5.15 => 4.5.15 
    @vue/cli-plugin-eslint: ^4.5.15 => 4.5.15 
    @vue/cli-plugin-pwa: ^4.5.15 => 4.5.15 
    @vue/cli-service: ^4.5.15 => 4.5.15 
    @vue/compiler-sfc: 3.2.26 => 3.2.26 
    vue: ^3.2.26 => 3.2.26 
    vue-cli-plugin-i18n: ^2.3.1 => 2.3.1 
    vue-cli-plugin-windicss: ~1.1.2 => 1.1.2 
    vue-i18n: ^9.2.0-beta.25 => 9.2.0-beta.25 
    vue-router: ^4.0.12 => 4.0.12
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kazupon** [comment]
Thank you for your feedback!

The `devtools-if` and `vue-devtools` entries in the production build are intentional.

Especialy, the vue-devtools plugin code (package) to support debug using vue-devtools, but in fact, those codes are mostly removed during production build. What remains are constants that are referenced in code outside of the vue-devtools plugin. This is why they are not tree-shaken and remain. This is why they are not shaken. In fact, during the development of vue-i18n-next, we have tuned the code so that it is tree-shaken to the very limit.

Thanks!
