### ISSUE TITLE
[ESLint] Allow internationalization in v-html but also sanitize against XSS attack vulnerability

### ISSUE THREAD

**Issue by Mouradif** [intlify/vue-i18n-next#893]
### Clear and concise description of the problem

Right now if I use `v-html="$t('some.translation.key')"`, eslint warns me that `Using $t on 'v-html' directive can lead to XSS attack  @intlify/vue-i18n/no-v-html`.

In some situation if you want to localize a whole paragraph with lots of `<strong>`, `<em>`, `<spans>`, etc... it's a bit tedious to put everything in variables to bind them and it would be so much simpler to just be allowed to use

`<p v-html="$t('some.translation.key')" />`

For example if your English version is 

```
<b>Warning!</b> You <b>do not</b> have <b>permission</b> to load <b>this page</b>. It's <b>harder</b> than I thought to <em>improvize</em> a <b style="color: black;">relevant</b> <em>example</em>. Blabla
```

And your French version is 

```
<b>Attention!</b> Vous n'avez <b>pas</b> <b>la permission</b> de charger <b>cette page</b>. C'est <b>plus dur</b> que je le pensais <em>d'improviser</em> un exemple <b style="color: black;">pertinent</b>. Blabla
```

it just seems too sad to not take advantage of `v-html`.

### Suggested solution

Solutions to sanitize the HTML you give to `v-html` exist. There are packages like

https://github.com/Vannsl/vue-3-sanitize

https://github.com/chantouchsek/v-sanitize

https://github.com/daichirata/vue-sanitize

But it may even be worth implementing it inside this package. 

### Alternative

Right now besides ignoring the warning, I don't see what else can be done

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by kazupon** [comment]
Thank you for your suggestion!
You can use the `i18n-t` component. :)
https://vue-i18n.intlify.dev/guide/advanced/component.html#component-interpolation

IMO, If you are fetching i18n resources from a trusted source, such as bundling i18n resources or hosting them on your own server, you can use `v-html`.

i18n resources can be dynamically imported and used. What happens if the hosting is from an untrusted source? With that in mind, it makes sense to lint the use of `v-html` with eslint.

Thanks!
